### ISSUE TITLE
Slack API Tester is set off when a message happens in a DM

### ISSUE THREAD

**Issue by stalltron** [docmarionum1/slack-archive-bot#10]
This has been happening from time to time and I've no just traced it to the slack-archive-bot. When I type a message in a DM, the Slack API Tester rattles off "No results found." See the screenshots below. What might be going on here?

![screen shot 2018-05-22 at 3 30 39 pm](https://user-images.githubusercontent.com/23216491/40369375-bd56c04a-5dd5-11e8-861d-a4e648761fad.png)
![screen shot 2018-05-22 at 3 30 20 pm](https://user-images.githubusercontent.com/23216491/40369376-bd783e1e-5dd5-11e8-9973-f67e28bdb8a5.png)

**Comment by docmarionum1** [comment]
Odd.  Is Slack API Tester the name of your archive bot? 
Did you somehow add the bot user to a DM with another user? I didn't think that was possible.

The only path into `handle_query` which returns that error is if the message is in a DM channel.  It only checks if it's a DM, not who the DM is between.  But, as far as I understood, a bot wouldn't be listening to messages in a DM between two other users.  

I have a fix that I think would ensure it only responds in DMs to itself, but I don't know how I would test it because I don't know how to get it into another DM, if that is indeed the problem.

**Comment by stalltron** [comment]
Thought I answered this earlier. Slack API Tester is a Slack tool that I believe is enabled automatically so that apps can call the Slack API. Name of my archive bot is timescale_ab.

Did not add the bot to private DMs.

**Comment by docmarionum1** [comment]
I don't have Slack API Tester and couldn't find any documentation about it.  Do you have any docs that I can see about setting it up?

As I said, I think I have the fix but I can't recreate your issue to test it.

**Comment by rjbergerud** [comment]
I found the issue had to do at least partly with messages being responded too only if the user name wasn't bot, however the user name for my bot seemed to be `Slack API Tester`, so the bot would start trying to respond to the same messages it just put out and loop.

**Comment by docmarionum1** [comment]
Oh, how did you create the slack integration? Is it a bot or an app? 

@stalltron @rjbergerud

**Comment by rjbergerud** [comment]
@docmarionum1 I was setting up the bot following this guide
"Setting up your bot users"
https://api.slack.com/bot-users
So its set up as a bot within an app.

But then, I used the Slack PI Legacy token
https://api.slack.com/custom-integrations/legacy-tokens

**Comment by docmarionum1** [comment]
I'm still baffled by how you two got that.  I created a bot using an app as you did.  But it still shouldn't be active in DMs between two human users.  Is there a way to invite a bot to a DM?

**Comment by stalltron** [comment]
@docmarionum1 no, I don't think so. It seems the bot is triggering the API Tester somehow...

**Comment by maxkan** [comment]
the issue is still there and it makes the bot unusable. each time you search for something it first gives you search results and then goes to endless "not found" loop. Bot name is "history", The search response goes under app name: "History", capital 'H'. 
Also here is what I see in the log: 
![image](https://user-images.githubusercontent.com/1884210/47961537-d8ebd980-dfda-11e8-9b63-065849398f4a.png)

**Comment by alehkot** [comment]
Bot is trying to reply to its own messages. I suggest trying to resolve the issue by changing [this line](https://github.com/docmarionum1/slack-archive-bot/blob/master/archivebot.py#L252)
to 
`if event['type'] == 'message' and ('subtype' not in event or event['subtype'] != 'bot_message'):`
It works on my local :)

**Comment by docmarionum1** [comment]
@maxkan A recent change, #14 allows you to specify the username of the bot, which, I think, will fix that issue. Have you tried this?

If not, try running with the flag `-b History`.

I've never actually been able to replicate this issue after setting up the app in a couple of different methods, so I can't verify that it in fact works, but it looks like it should.

**Comment by alehkot** [comment]
@docmarionum1 Thanks, your solution works on my env as well. I think it's a little bit confusing that App name should be used as is instead of using its machine name, i.e. if an app name is "Acme Test Bot", the machine name is "acme_test_bot", but parameter -b should be used with "Acme Test Bot".

**Comment by docmarionum1** [comment]
Seems to be fixed.
